my_string = input('Введите любую строку: ')
print(my_string + ' - ' + str(len(my_string)) + ' символов')
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', '_'))
print(my_string[0])
print(my_string[-1])